
POST http://localhost:8080/public/login
Content-Type: application/json

{
  "userid" : "test",
  "password" : "1234"
}

###

GET http://localhost:8080/userinfo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdCIsImlhdCI6MTcyNTM3Mzg2MywiZXhwIjoxNzI1Mzc3NDYzLCJyb2xlcyI6IlJPTEVfVVNFUiJ9.KibaOSh1DyTGgarp3GOwDqXLwQf5OY7OPEXaMier05HCHll8emSMiF1g0XfsTOWkR6pfRvydLjIFIv9tZHYdCw

###
GET http://localhost:8080/ocr/run-python
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdCIsImlhdCI6MTcyNjczNTQ0NiwiZXhwIjoxNzI2NzM5MDQ2LCJyb2xlcyI6IlJPTEVfVVNFUiJ9.4tjk-F4YCdft2Kxp6s5GRr-FH3hGbi8f0ta694fRzcEKG9AlYNRODwcpR5k340CNa0aV0r3KBCD2xSSpp2D1rw

###

POST http://localhost:8080/admin/process/1
Content-Type: application/json

{
  "title": "개인회생"
}

###
POST http://localhost:8080/board/posts
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdCIsImlhdCI6MTcyOTQ5MDI3MSwiZXhwIjoxNzI5NDkzODcxLCJyb2xlcyI6IlJPTEVfVVNFUiJ9.5p_QM7-n_nR6MWYA3KF2L4s3BFbCpRLD5wlK8KxKuVT9NUxJ1d3ZEyOq0IChgOXH8r1ywKZjf6MXuGrdGNUvFQ

<> 2024-10-21T145921.200.json

###
POST http://localhost:8080/board/admin/posts
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpZCI6MSwic3ViIjoidGVzdCIsImlhdCI6MTcyOTQ5MDI3MSwiZXhwIjoxNzI5NDkzODcxLCJyb2xlcyI6IlJPTEVfVVNFUiJ9.5p_QM7-n_nR6MWYA3KF2L4s3BFbCpRLD5wlK8KxKuVT9NUxJ1d3ZEyOq0IChgOXH8r1ywKZjf6MXuGrdGNUvFQ
