POST http://localhost:8080/login
Content-Type: application/json

{
  "id" : "po",
  "password" : "examplePasswordHash"
}
###
POST http://localhost:8080/api/join
Content-Type: application/json

{
  "id" : "po",
  "password" : "123a",
  "phonenum": "01029284502",
  "username": "이병"
}